### ISSUE TITLE
[Task] [Client] 메인페이지 기능 구현 - Content Cards 컴포넌트 생성 (2)

### ISSUE THREAD

**Issue by namooni** [codestates/Subllet#12]
### ISSUE
- Group:  `cllient`
- Type: `feature`
- Detail: 메인페이지 내 COntent Cards 컴포넌트 생성

### TODO
1. [x]  Content Card 컴포넌트 생성 (Shopping)
2. [x]  Content Card 컴포넌트 생성 (Life)
3. [x]  Content Card 컴포넌트 생성 (Pick)

### `3h`
