### ISSUE TITLE
[Task] [client] 상세페이지 기능 구현 - ServiceContent 컴포넌트 생성

### ISSUE THREAD

**Issue by kkangtaeng** [codestates/Subllet#13]
### ISSUE

- Group: `client`
- Type: `feature`
- Detail: 상세페이지 ServiceContent 컴포넌트 가격 및 서비스 랜더링 및 링크 버튼 구현

### TODO

- [x]  가격에 클릭칸 생성 및 클릭시 해당 서비스 정보 랜더링
- [x]  default로 제일 첫번째 가격 선택
- [x]  구독하러 가기 버튼 클릭시 해당 서비스 링크로 이동하는 버튼 구현

### `3h`
