### ISSUE TITLE
[Task] SR 진행 (1)

### ISSUE THREAD

**Issue by namooni** [codestates/Subllet#2]
### ISSUE
- Group: `SR`
- Type: `requirement`
- Detail: sr progress

### TODO
1. [x]  프로젝트 아이디어 및 프로젝트명 선정
2. [x]  사용 스택 결정
3. [x]  서비스 범위 및 기능 선정
4. [x]  프로토타입 기획
5. [x]  스키마 작성
6. [x]  API 작성
