### ISSUE TITLE
[Task] [Client] 메인페이지 기능 구현 - MainCard 컴포넌트 생성 (1)

### ISSUE THREAD

**Issue by namooni** [codestates/Subllet#6]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 메인페이지 내 MainCard 컴포넌트 생성

### TODO
1. [x]  배경 이미지 삽입
2. [x]  유저 정보에서 Nickname 받아와서 표기
3. [x]  Nickname 클릭시 MySubllet 이동
4. [x]  유저 정보에서 ProfileImg 받아와서 표기
