### ISSUE TITLE
[Task] [Client] 메인페이지 기능 구현 - MainCard 컴포넌트 생성 (2)

### ISSUE THREAD

**Issue by namooni** [codestates/Subllet#7]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 메인페이지 내 MainCard 컴포넌트 생성

### TODO
1. [x]  유저 정보에서 TotalPrice 받아와서 표기
2. [x]  유저 정보에서 구독목록 받아와서 표기
3. [x]  '구독을 추가하세요' 버튼 클릭시 MySubllet 이동
