### ISSUE TITLE
[Task] [client] 상세페이지 기능 구현 - InnerImage 컴포넌트 생성 (1)

### ISSUE THREAD

**Issue by kkangtaeng** [codestates/Subllet#9]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 상세페이지 InnerImage 컴포넌트 스크랩 기능 구현

### TODO
1. [x] 상세페이지 정보 불러와 컴포넌트 내에 랜더링
2. [x] 스크랩 구독 버튼 아이콘 생성 및 해당 서비스 스크랩한 수 구현
3. [x] 스크랩 구독 버튼 아이콘 클릭시 내 스크랩 목록에 추가

### `3h`
